services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: acara-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acara
    ports:
      - "3310:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - acara-mysql-db:/var/lib/mysql
volumes:
  acara-mysql-db: